import React, { useMemo, useRef, useState } from "react";
import { useNavigate } from "react-router-dom";
import { useWorkshop } from "../context/WorkshopContext.jsx";

const CATEGORIES = ["Pantalla", "Audio", "Electrodoméstico", "Microondas", "Videocámara", "Laptop", "Consola", "Monitor", "Otro"];
const ACCESSORIES = ["Cable AC", "Cable HDMI", "Cable USB", "Cable USB-C", "Control remoto", "Baterías", "Base de mesa", "Rack de pared", "Cargador", "Adaptador", "Estuche", "Cable de audio", "Sin accesorios", "Otro"];
const clean = (value) => String(value || "").trim().replace(/\s+/g, " ");
const catalogName = (item) => typeof item === "string" ? item : item?.nombre || "";

export default function NuevaOrdenView({ onOrdenCreada }) {
  const { clientes = [], equipos = [], marcas = [], modelos = [], accesorios = [], addCliente, addEquipo, addMarca, addModelo, addAccesorio, addOrden } = useWorkshop();
  const navigate = useNavigate(); const fileRef = useRef(null);
  const [client, setClient] = useState(null), [equipment, setEquipment] = useState(null);
  const [clientQuery, setClientQuery] = useState(""), [equipmentQuery, setEquipmentQuery] = useState("");
  const [openClients, setOpenClients] = useState(false), [openEquipment, setOpenEquipment] = useState(false);
  const [clientForm, setClientForm] = useState(false), [equipmentForm, setEquipmentForm] = useState(false);
  const [newClient, setNewClient] = useState({ tipo_cliente: "Persona", identificacion: "", nombre: "", telefono: "", email: "" });
  const [newEquipment, setNewEquipment] = useState({ tipo: "Pantalla", marca: "", modelo: "", serie: "" });
  const [openBrands, setOpenBrands] = useState(false), [openModels, setOpenModels] = useState(false);
  const [accessoryQuery, setAccessoryQuery] = useState(""), [openAccessories, setOpenAccessories] = useState(false), [selectedAccessories, setSelectedAccessories] = useState([]);
  const [warranty, setWarranty] = useState(false), [advance, setAdvance] = useState(0), [work, setWork] = useState(""), [inspection, setInspection] = useState(""), [files, setFiles] = useState([]);
  const [errors, setErrors] = useState({}), [saving, setSaving] = useState(""), [toast, setToast] = useState("");
  const clientMatches = useMemo(() => { const q = clientQuery.toLowerCase(); return clientes.filter((x) => !q || [x.nombre, x.apellido, x.identificacion, x.telefono].join(" ").toLowerCase().includes(q)).slice(0, 6); }, [clientes, clientQuery]);
  const equipmentMatches = useMemo(() => { const q = equipmentQuery.toLowerCase(); return equipos.filter((x) => !q || [x.serie, x.marca, x.modelo].join(" ").toLowerCase().includes(q)).slice(0, 6); }, [equipos, equipmentQuery]);
  const brandList = useMemo(() => marcas.map(catalogName).filter(Boolean), [marcas]);
  const modelCatalog = useMemo(() => {
    const combined = [
      ...modelos,
      ...equipos.filter((item) => clean(item.marca) && clean(item.modelo)).map((item) => ({ nombre: clean(item.modelo), marcaNombre: clean(item.marca), source: "equipment" }))
    ];
    const seen = new Set();
    return combined.filter((item) => {
      const key = `${clean(item?.marcaNombre || item?.marca).toLowerCase()}::${clean(item?.nombre || item?.modelo).toLowerCase()}`;
      if (!key || key === "::" || seen.has(key)) return false;
      seen.add(key);
      return true;
    });
  }, [modelos, equipos]);
  const brandMatches = brandList.filter((x) => x.toLowerCase().includes(newEquipment.marca.toLowerCase())).slice(0, 6);
  const modelMatches = modelCatalog.filter((x) => clean(x.marcaNombre || x.marca).toLowerCase() === clean(newEquipment.marca).toLowerCase() && clean(x.nombre || x.modelo).toLowerCase().includes(clean(newEquipment.modelo).toLowerCase())).slice(0, 6);
  const accessoriesList = [...new Set([...ACCESSORIES, ...accesorios.map(catalogName).filter(Boolean)])];
  const accessoryMatches = accessoriesList.filter((x) => x.toLowerCase().includes(accessoryQuery.toLowerCase())).slice(0, 8);
  const selectClient = (value) => { setClient(value); setClientQuery(value.nombre || ""); setOpenClients(false); setErrors((x) => ({ ...x, client: "" })); };
  const selectEquipment = (value) => { setEquipment(value); setEquipmentQuery([value.marca, value.modelo, value.serie].filter(Boolean).join(" · ")); setOpenEquipment(false); setErrors((x) => ({ ...x, equipment: "" })); };
  const chooseAccessory = async (value) => { const item = clean(value); if (!item) return; if (!accessoriesList.some((x) => x.toLowerCase() === item.toLowerCase())) await addAccesorio(item); setSelectedAccessories((items) => item === "Sin accesorios" ? [item] : items.includes(item) ? items : [...items.filter((x) => x !== "Sin accesorios"), item]); setAccessoryQuery(""); setOpenAccessories(false); };
  const createBrand = async () => { const name = clean(newEquipment.marca); if (!name) return; setSaving("brand"); try { const created = await addMarca(name); if (!created) throw new Error("Marca inválida"); setNewEquipment((current) => ({ ...current, marca: catalogName(created), modelo: "" })); setOpenBrands(false); setErrors((current) => ({ ...current, equipmentForm: "" })); } catch (error) { console.error("Error al crear marca", error); setErrors((current) => ({ ...current, equipmentForm: "No se pudo crear la marca. Inténtalo nuevamente." })); } finally { setSaving(""); } };
  const createModel = async () => { const name = clean(newEquipment.modelo), brand = clean(newEquipment.marca); if (!brand) return setErrors((current) => ({ ...current, equipmentForm: "Selecciona una marca antes de crear el modelo." })); if (!name) return; setSaving("model"); try { const created = await addModelo({ nombre: name, marcaNombre: brand }); if (!created) throw new Error("Modelo inválido"); setNewEquipment((current) => ({ ...current, modelo: catalogName(created) })); setOpenModels(false); setErrors((current) => ({ ...current, equipmentForm: "" })); } catch (error) { console.error("Error al crear modelo", error); setErrors((current) => ({ ...current, equipmentForm: "No se pudo crear el modelo. Inténtalo nuevamente." })); } finally { setSaving(""); } };
  const saveClient = async () => { const email = clean(newClient.email); if (!newClient.tipo_cliente || !clean(newClient.nombre) || !clean(newClient.identificacion) || !clean(newClient.telefono)) return setErrors((x) => ({ ...x, clientForm: "Completá tipo, cédula, nombre completo y teléfono." })); if (email && !/^\S+@\S+\.\S+$/.test(email)) return setErrors((x) => ({ ...x, clientForm: "Ingresa un correo electrónico válido." })); setSaving("client"); try { const created = await addCliente({ ...newClient, email }); selectClient(created); setNewClient({ tipo_cliente: "Persona", identificacion: "", nombre: "", telefono: "", email: "" }); setClientForm(false); setErrors((x) => ({ ...x, clientForm: "" })); } catch (error) { console.error("Error al guardar cliente", error); setErrors((x) => ({ ...x, clientForm: "No se pudo guardar el cliente. Inténtalo nuevamente." })); } finally { setSaving(""); } };
  const saveEquipment = async () => {
    const { tipo, marca, modelo, serie } = newEquipment;
    if (!tipo || !clean(marca) || !clean(modelo) || !clean(serie)) {
      return setErrors((current) => ({ ...current, equipmentForm: "Completá categoría, marca, modelo y número de serie." }));
    }

    const serial = clean(serie);
    const existing = equipos.find((item) => clean(item.serie).toLowerCase() === serial.toLowerCase());
    if (existing) {
      selectEquipment(existing);
      return setErrors((current) => ({ ...current, equipmentForm: "Ya existe un equipo registrado con este número de serie. Se seleccionó el equipo existente." }));
    }

    setSaving("equipment");
    try {
      const normalizedBrand = clean(marca);
      const normalizedModel = clean(modelo);
      if (!brandList.some((item) => item.toLowerCase() === normalizedBrand.toLowerCase())) {
        await addMarca(normalizedBrand);
      }
      const modelExists = modelCatalog.some((item) => (
        clean(item.marcaNombre || item.marca).toLowerCase() === normalizedBrand.toLowerCase()
        && clean(item.nombre || item.modelo).toLowerCase() === normalizedModel.toLowerCase()
      ));
      if (!modelExists) await addModelo({ nombre: normalizedModel, marcaNombre: normalizedBrand });

      const created = await addEquipo({
        cliente_id: client?.id || "",
        tipo,
        marca: normalizedBrand,
        modelo: normalizedModel,
        serie: serial,
        accesorios: selectedAccessories.join(", ") || "NINGUNO"
      });
      selectEquipment(created);
      setNewEquipment({ tipo: "Pantalla", marca: "", modelo: "", serie: "" });
      setEquipmentForm(false);
      setErrors((current) => ({ ...current, equipmentForm: "" }));
    } catch (error) {
      console.error("Error al guardar equipo", error);
      setErrors((current) => ({ ...current, equipmentForm: "No se pudo guardar el equipo. Inténtalo nuevamente." }));
    } finally {
      setSaving("");
    }
  };
  const attach = (list) => setFiles((items) => [...items, ...Array.from(list || []).map((file) => ({ id: `${file.name}-${file.lastModified}-${Math.random()}`, file, preview: file.type.startsWith("image/") ? URL.createObjectURL(file) : "" }))]);
  const removeFile = (id) => setFiles((items) => { const found = items.find((x) => x.id === id); if (found?.preview) URL.revokeObjectURL(found.preview); return items.filter((x) => x.id !== id); });
  const serializeFiles = () => Promise.all(files.map(({ file }) => new Promise((resolve) => { if (!file.type.startsWith("image/")) return resolve({ id: `arc-${Date.now()}-${file.name}`, nombre: file.name, tipo: file.type, tamano: `${(file.size / 1024 / 1024).toFixed(2)} MB`, fecha: new Date().toLocaleDateString("es-CR"), vistaPrevia: null }); const reader = new FileReader(); reader.onload = () => resolve({ id: `arc-${Date.now()}-${file.name}`, nombre: file.name, tipo: file.type, tamano: `${(file.size / 1024 / 1024).toFixed(2)} MB`, fecha: new Date().toLocaleDateString("es-CR"), vistaPrevia: reader.result }); reader.readAsDataURL(file); })));
  const save = async (draft) => { const next = {}; if (!draft && !client) next.client = "Seleccioná un cliente."; if (!draft && !equipment) next.equipment = "Seleccioná un equipo."; if (!draft && !work.trim()) next.work = "Indicá el trabajo solicitado."; setErrors(next); if (Object.keys(next).length) return; setSaving(draft ? "draft" : "create"); try { const order = await addOrden({ cliente_id: client?.id || "", equipo_id: equipment?.id || "", estado_actual: draft ? "BORRADOR" : "RECEPCIÓN", etapa_categoria: draft ? "BORRADOR" : "ENTRADA", trabajo_solicitado: work || "Borrador de orden", descripcion_estado: inspection || "Sin inspección visual registrada.", garantia: warranty, adelanto: Math.max(0, Number(advance) || 0), accesorios: selectedAccessories.length ? selectedAccessories.join(", ") : "SIN ACCESORIOS", archivos: await serializeFiles() }); onOrdenCreada?.(order); if (draft) setToast(`✓ Borrador #${order.numero} guardado correctamente`); else { setToast(`✓ Orden #${order.numero} creada correctamente`); window.setTimeout(() => navigate(`/ordenes/${order.numero}`, { replace: true }), 300); } } catch (error) { setErrors({ form: error.message || "No fue posible guardar la orden." }); } finally { setSaving(""); } };
  return <main className="new-order-page page-container bg-slate-50"><section className="new-order-card mx-auto max-w-6xl rounded-2xl border border-slate-200 bg-white p-5 shadow-sm md:p-6"><header className="mb-5 border-b border-slate-100 pb-4"><h1 className="text-xl font-extrabold text-slate-900">Nueva Orden de Servicio Técnico</h1><p className="mt-1 text-sm text-slate-500">Recepción y registro del equipo.</p></header>{toast && <p role="status" className="mb-3 rounded-lg bg-emerald-50 p-3 text-sm font-semibold text-emerald-800">{toast}</p>}{errors.form && <p role="alert" className="mb-3 text-sm text-red-700">{errors.form}</p>}
    <div className="grid gap-5 border-b border-slate-100 pb-5 md:grid-cols-2"><Finder title="Cliente" action="+ Nuevo Cliente" value={clientQuery} setValue={setClientQuery} placeholder="Buscar por nombre, cédula o teléfono..." open={openClients} setOpen={setOpenClients} matches={clientMatches} render={(x) => <><b>{x.nombre}</b><small>Cédula: {x.identificacion || "—"} · WhatsApp: {x.telefono || "—"}</small></>} select={selectClient} selected={client && <Summary title={client.nombre} lines={[`Cédula: ${client.identificacion || "—"}`, `WhatsApp: ${client.telefono || "—"}`]} />} onAction={() => setClientForm(true)} error={errors.client} /><Finder title="Equipo" action="+ Registrar Equipo" value={equipmentQuery} setValue={setEquipmentQuery} placeholder="Buscar por serie, marca o modelo..." open={openEquipment} setOpen={setOpenEquipment} matches={equipmentMatches} render={(x) => <><b>{x.marca || "—"} · {x.modelo || "—"}</b><small>Serie: {x.serie || "—"}</small></>} select={selectEquipment} selected={equipment && <Summary title={`${equipment.marca || "—"} ${equipment.modelo || ""}`} lines={[`Tipo: ${equipment.tipo || "—"}`, `Serie: ${equipment.serie || "—"}`]} />} onAction={() => setEquipmentForm(true)} error={errors.equipment} /></div>
    <section className="py-5"><h2 className="mb-4 text-sm font-extrabold uppercase tracking-wide text-slate-700">Datos de la orden</h2><div className="grid gap-4 md:grid-cols-2"><div className="grid grid-cols-2 gap-3"><label className="rounded-xl border border-slate-200 bg-slate-50 p-3 text-sm font-semibold text-slate-700">Garantía<span className="mt-2 flex items-center gap-2"><button type="button" role="switch" aria-checked={warranty} onClick={() => setWarranty((x) => !x)} className={`relative h-6 w-11 rounded-full ${warranty ? "bg-sky-600" : "bg-slate-300"}`}><span className={`absolute top-1 h-4 w-4 rounded-full bg-white transition ${warranty ? "left-6" : "left-1"}`} /></button>{warranty ? "Con garantía" : "Sin garantía"}</span></label><label className="text-sm font-semibold text-slate-700">Costo de revisión / Adelanto recibido<span className="relative mt-1 block"><i className="absolute left-3 top-2.5 not-italic text-slate-500">₡</i><input type="number" min="0" value={advance} onChange={(e) => setAdvance(e.target.value)} className="w-full rounded-xl border border-slate-300 bg-slate-50 py-2 pl-7 pr-3" /></span></label></div><div /><label className="text-sm font-semibold text-slate-700">Trabajo solicitado / Motivo de ingreso *<input value={work} onChange={(e) => setWork(e.target.value)} className="mt-1 w-full rounded-xl border border-slate-300 bg-slate-50 px-3 py-2" placeholder="Ej. Televisor no enciende" />{errors.work && <small className="text-red-600">{errors.work}</small>}</label><label className="text-sm font-semibold text-slate-700">Inspección visual / Estado del equipo<textarea rows="3" value={inspection} onChange={(e) => setInspection(e.target.value)} className="mt-1 w-full rounded-xl border border-slate-300 bg-slate-50 px-3 py-2" placeholder="Rayones, golpes y estado visible..." /></label></div><Accessories selected={selectedAccessories} query={accessoryQuery} setQuery={setAccessoryQuery} open={openAccessories} setOpen={setOpenAccessories} matches={accessoryMatches} choose={chooseAccessory} remove={(item) => setSelectedAccessories((x) => x.filter((v) => v !== item))} /></section>
    <section className="border-t border-slate-100 py-5"><h2 className="mb-3 text-sm font-extrabold uppercase tracking-wide text-slate-700">Archivos / fotografías de ingreso</h2><button type="button" onClick={() => fileRef.current?.click()} onDragOver={(e) => e.preventDefault()} onDrop={(e) => { e.preventDefault(); attach(e.dataTransfer.files); }} className="flex w-full flex-col items-center rounded-xl border-2 border-dashed border-slate-300 bg-slate-50 py-5 text-sm text-slate-500 hover:border-sky-400"><b>📎 Arrastrar fotografías aquí</b><span>o seleccionar archivos</span></button><input ref={fileRef} type="file" accept="image/*,.pdf" multiple className="hidden" onChange={(e) => attach(e.target.files)} />{files.length > 0 && <div className="mt-3 flex flex-wrap gap-3">{files.map((x) => <div key={x.id} className="relative w-24 rounded-lg border p-1"><button type="button" onClick={() => removeFile(x.id)} aria-label={`Eliminar ${x.file.name}`} className="absolute right-1 top-1 text-red-600">×</button>{x.preview ? <img src={x.preview} alt="Vista previa" className="h-16 w-full object-cover" /> : <div className="grid h-16 place-items-center">📄</div>}<small className="block truncate">{x.file.name}</small></div>)}</div>}</section><footer className="flex flex-wrap justify-end gap-3 border-t border-slate-100 pt-5"><button type="button" onClick={() => navigate(-1)} className="rounded-xl border border-slate-300 px-4 py-2 text-sm font-bold">Cancelar</button><button type="button" disabled={!!saving} onClick={() => save(true)} className="rounded-xl bg-sky-100 px-4 py-2 text-sm font-bold text-sky-800">{saving === "draft" ? "Guardando..." : "💾 Guardar borrador"}</button><button type="button" disabled={!!saving} onClick={() => save(false)} className="rounded-xl bg-orange-500 px-4 py-2 text-sm font-bold text-white">{saving === "create" ? "Creando orden..." : "✓ Crear orden"}</button></footer></section>
    {clientForm && <Modal title="Nuevo cliente" close={() => setClientForm(false)}><div className="grid gap-3 sm:grid-cols-2"><Label text="Tipo de cliente"><select value={newClient.tipo_cliente} onChange={(e) => setNewClient({ ...newClient, tipo_cliente: e.target.value })}><option>Persona</option><option>Empresa</option></select></Label><Label text="Cédula"><input value={newClient.identificacion} onChange={(e) => setNewClient({ ...newClient, identificacion: e.target.value })} /></Label><Label text="Nombre completo"><input value={newClient.nombre} onChange={(e) => setNewClient({ ...newClient, nombre: e.target.value })} /></Label><Label text="Teléfono / WhatsApp"><input value={newClient.telefono} onChange={(e) => setNewClient({ ...newClient, telefono: e.target.value })} /></Label><Label text="Correo electrónico"><input type="email" value={newClient.email} onChange={(e) => setNewClient({ ...newClient, email: e.target.value })} /></Label></div>{errors.clientForm && <p className="mt-2 text-sm text-red-600">{errors.clientForm}</p>}<Actions cancel={() => setClientForm(false)} save={saveClient} label={saving === "client" ? "Guardando..." : "Guardar"} disabled={saving === "client"} /></Modal>}
    {equipmentForm && <Modal title="Registrar nuevo equipo" close={() => setEquipmentForm(false)}><div className="grid gap-4 sm:grid-cols-2"><Label text="Categoría / Tipo *"><select value={newEquipment.tipo} onChange={(e) => setNewEquipment({ ...newEquipment, tipo: e.target.value })}>{CATEGORIES.map((x) => <option key={x}>{x}</option>)}</select></Label><Label text="N° Serie físico *"><input value={newEquipment.serie} onChange={(e) => setNewEquipment({ ...newEquipment, serie: e.target.value })} /></Label><Label text="Marca *"><input value={newEquipment.marca} onFocus={() => setOpenBrands(true)} onChange={(e) => { setNewEquipment({ ...newEquipment, marca: e.target.value, modelo: "" }); setOpenBrands(true); }} />{openBrands && <Dropdown items={brandMatches} choose={(x) => { setNewEquipment({ ...newEquipment, marca: x }); setOpenBrands(false); }} create={clean(newEquipment.marca) && !brandList.some((x) => x.toLowerCase() === clean(newEquipment.marca).toLowerCase()) ? `Crear marca "${clean(newEquipment.marca)}"` : ""} onCreate={createBrand} saving={saving === "brand"} />}</Label><Label text="Modelo *"><input disabled={!newEquipment.marca} value={newEquipment.modelo} onFocus={() => setOpenModels(true)} onChange={(e) => { setNewEquipment({ ...newEquipment, modelo: e.target.value }); setOpenModels(true); }} />{openModels && newEquipment.marca && <Dropdown items={modelMatches.map((x) => x.nombre)} choose={(x) => { setNewEquipment({ ...newEquipment, modelo: x }); setOpenModels(false); }} create={clean(newEquipment.modelo) && !modelMatches.some((x) => clean(x.nombre).toLowerCase() === clean(newEquipment.modelo).toLowerCase()) ? `Crear modelo "${clean(newEquipment.modelo)}"` : ""} onCreate={createModel} saving={saving === "model"} />}</Label></div>{errors.equipmentForm && <p className="mt-2 text-sm text-red-600">{errors.equipmentForm}</p>}<Actions cancel={() => setEquipmentForm(false)} save={saveEquipment} label={saving === "equipment" ? "Guardando..." : "Guardar"} disabled={!!saving} /></Modal>}
  </main>;
}
function Finder({ title, action, onAction, value, setValue, placeholder, open, setOpen, matches, render, select, selected, error }) { return <section className="relative"><div className="mb-2 flex justify-between"><h2 className="text-sm font-extrabold uppercase text-slate-700">{title}</h2><button type="button" onClick={onAction} className="font-bold text-sky-700">{action}</button></div><input value={value} onFocus={() => setOpen(true)} onChange={(e) => { setValue(e.target.value); setOpen(true); }} placeholder={placeholder} className="w-full rounded-xl border border-slate-300 bg-slate-50 px-3 py-2.5 text-sm" />{open && <div className="absolute z-20 mt-1 max-h-52 w-full overflow-auto rounded-xl border bg-white p-1 shadow-lg">{matches.length ? matches.map((x) => <button type="button" key={x.id} onClick={() => select(x)} className="block w-full rounded-lg px-3 py-2 text-left text-sm hover:bg-sky-50">{render(x)}</button>) : <p className="p-3 text-sm text-slate-500">Sin coincidencias.</p>}</div>}{selected}<small className="text-red-600">{error}</small></section>; }
function Summary({ title, lines }) { return <div className="mt-2 rounded-lg bg-emerald-50 p-2 text-sm text-emerald-900"><b>✓ {title}</b>{lines.map((x) => <small key={x} className="block">{x}</small>)}</div>; }
function Accessories({ selected, query, setQuery, open, setOpen, matches, choose, remove }) { return <div className="relative mt-4"><label className="text-sm font-semibold text-slate-700">Accesorios entregados</label><div className="mt-1 flex flex-wrap gap-2 rounded-xl border border-slate-300 bg-slate-50 p-2">{selected.map((x) => <button type="button" key={x} onClick={() => remove(x)} className="rounded-full bg-sky-100 px-2 py-1 text-xs text-sky-800">{x} ×</button>)}<input value={query} onFocus={() => setOpen(true)} onChange={(e) => { setQuery(e.target.value); setOpen(true); }} placeholder="Escribir o seleccionar accesorios..." className="min-w-48 flex-1 bg-transparent text-sm outline-none" /></div>{open && <div className="absolute z-20 mt-1 max-h-48 w-full overflow-auto rounded-xl border bg-white p-1 shadow-lg">{matches.map((x) => <button type="button" key={x} onClick={() => choose(x)} className="block w-full rounded-lg px-3 py-2 text-left text-sm hover:bg-sky-50">{x}</button>)}{clean(query) && !matches.some((x) => x.toLowerCase() === clean(query).toLowerCase()) && <button type="button" onClick={() => choose(query)} className="block w-full border-t px-3 py-2 text-left font-bold text-sky-700">+ Crear accesorio "{clean(query)}"</button>}</div>}</div>; }
function Dropdown({ items, choose, create, onCreate, saving = false }) { return <div className="new-order-dropdown mt-1 max-h-40 w-full overflow-auto rounded-lg border p-1 shadow-lg">{items.map((x) => <button type="button" key={x} onClick={() => choose(x)} className="block w-full rounded px-2 py-1.5 text-left text-sm hover:bg-sky-50">{x}</button>)}{create && <button type="button" disabled={saving} onClick={onCreate} className="block w-full border-t px-2 py-1.5 text-left text-sm font-bold text-sky-700">{saving ? "Guardando..." : `+ ${create}`}</button>}</div>; }
function Modal({ title, close, children }) { return <div onMouseDown={close} className="fixed inset-0 z-50 grid place-items-center bg-slate-950/40 p-4"><section onMouseDown={(e) => e.stopPropagation()} role="dialog" aria-modal="true" aria-label={title} className="new-order-modal w-full max-w-xl rounded-2xl bg-white p-5 shadow-xl"><header className="mb-4 flex justify-between"><h2 className="text-lg font-extrabold">{title}</h2><button type="button" onClick={close} aria-label="Cerrar">×</button></header>{children}</section></div>; }
function Label({ text, children }) { return <label className="grid gap-1 text-sm font-semibold text-slate-700">{text}{children}</label>; }
function Actions({ cancel, save, label, disabled = false }) { return <footer className="mt-5 flex justify-end gap-3"><button type="button" onClick={cancel} className="rounded-lg border px-3 py-2 font-bold">Cancelar</button><button type="button" onClick={save} disabled={disabled} className="rounded-lg bg-sky-600 px-3 py-2 font-bold text-white disabled:cursor-not-allowed disabled:opacity-60">{label}</button></footer>; }
