import i18n from "i18next";
import { initReactI18next } from "react-i18next";
import esBase from "./locales/es.json";
import enBase from "./locales/en.json";

const resources = {
  es: { translation: { ...esBase,
    "search.placeholder": "Buscar orden, cliente o equipo [/]", "action.newOrder": "Nueva Orden", "action.logout": "Salir", "action.language": "Cambiar idioma",
    "nav.dashboard": "General / Dashboard", "nav.agenda": "Agenda", "nav.serviceCenter": "Centro de Servicios", "nav.orders": "Órdenes de trabajo", "nav.equipment": "Equipos (Historial)", "nav.clients": "Clientes (Historial)", "nav.statistics": "Estadísticas", "nav.quotes": "Cotizaciones", "nav.users": "Usuarios y permisos", "nav.products": "Productos", "nav.services": "Servicios"
    ,"orders.title": "Todas las órdenes", "orders.description": "Gestión completa del flujo de equipos en reparación — OptiFix Centro de Servicios", "orders.all": "Todas las órdenes", "orders.entry": "Entrada", "orders.progress": "En trámite", "orders.workshop": "En taller", "orders.delivered": "Salida / Entregado", "orders.action": "Acción", "orders.viewDetail": "Ver detalle"
    ,"page.dashboard": "Centro de Control y Operaciones", "page.agenda": "Agenda y Citas", "page.equipment": "Gestión de Equipos", "page.clients": "Directorio de Clientes", "page.statistics": "Panel de Estadísticas", "page.quotes": "Cotizaciones y Presupuestos", "page.users": "Usuarios y permisos", "page.products": "Catálogo de Repuestos", "page.services": "Gestión de Servicios", "page.landing": "Sistema de Gestión de Taller Electrónico"
    ,"dashboard.operational": "Taller operativo", "dashboard.monitoring": "Monitoreo unificado de servicio técnico, recepción, inventario y compromisos de entrega.", "dashboard.quickReceipt": "Boleta rápida", "dashboard.newServiceOrder": "Nueva orden de servicio", "dashboard.ordersInWorkshop": "Órdenes en taller", "dashboard.estimatedBilling": "Facturación estimada", "dashboard.technicalAgenda": "Agenda técnica", "dashboard.pendingQuotes": "Cotizaciones pendientes", "dashboard.inReception": "en recepción", "dashboard.inBench": "en banco", "dashboard.openOrderProducts": "Productos y servicios de órdenes abiertas", "dashboard.pendingFollowups": "Seguimientos operativos pendientes", "dashboard.customerConfirmation": "Requieren confirmación del cliente", "dashboard.automatedChannel": "Canal automatizado WhatsApp & SMS activo.", "dashboard.keepClientsInformed": "Mantén informados a tus clientes sobre cada cambio de estado.", "dashboard.viewHistory": "Ver historial", "dashboard.activeOrders": "Órdenes de trabajo activas", "dashboard.realTimeTracking": "Seguimiento en tiempo real por puesto de reparación", "dashboard.all": "Todas", "dashboard.reception": "Recepción", "dashboard.onBench": "En banco", "dashboard.ready": "Listas", "dashboard.orderDate": "OT / Fecha", "dashboard.equipmentFault": "Equipo y falla", "dashboard.client": "Cliente", "dashboard.status": "Estado", "dashboard.noEquipment": "Equipo sin registro", "dashboard.noClient": "Cliente sin registro", "dashboard.noPhone": "Sin teléfono", "dashboard.viewAllOrders": "Ver todas las órdenes de trabajo en cola", "dashboard.currentPriorities": "Prioridades actuales del taller", "dashboard.openAgenda": "Abrir agenda completa", "dashboard.repairBench": "Banco de reparación", "dashboard.noAssigned": "Sin equipos asignados", "dashboard.assignOrder": "Asigna una orden para iniciar un diagnóstico.", "dashboard.currentStatus": "Estado actual", "dashboard.available": "Disponible", "dashboard.clientFiles": "Clientes y fichas", "dashboard.equipmentRegistered": "Equipos registrados", "dashboard.serviceHistory": "registros con historial de servicio", "dashboard.serialTraceable": "equipos trazables por serie", "dashboard.pendingEstimates": "presupuestos en espera de aprobación"
  } },
  en: { translation: { ...enBase,
    "search.placeholder": "Search order, client or equipment [/]", "action.newOrder": "New Order", "action.logout": "Log out", "action.language": "Change language",
    "nav.dashboard": "General / Dashboard", "nav.agenda": "Schedule", "nav.serviceCenter": "Service Center", "nav.orders": "Work orders", "nav.equipment": "Equipment (History)", "nav.clients": "Clients (History)", "nav.statistics": "Statistics", "nav.quotes": "Quotes", "nav.users": "Users & permissions", "nav.products": "Products", "nav.services": "Services"
    ,"orders.title": "All work orders", "orders.description": "Complete management of the repair workflow — OptiFix Service Center", "orders.all": "All orders", "orders.entry": "Intake", "orders.progress": "In progress", "orders.workshop": "Workshop", "orders.delivered": "Dispatch / Delivered", "orders.action": "Action", "orders.viewDetail": "View details"
    ,"page.dashboard": "Control Center & Operations", "page.agenda": "Schedule & Appointments", "page.equipment": "Equipment Management", "page.clients": "Client Directory", "page.statistics": "Statistics Dashboard", "page.quotes": "Quotes & Estimates", "page.users": "Users & permissions", "page.products": "Parts Catalog", "page.services": "Service Management", "page.landing": "Electronic Workshop Management System"
    ,"dashboard.operational": "Workshop operational", "dashboard.monitoring": "Unified monitoring of technical service, intake, inventory and delivery commitments.", "dashboard.quickReceipt": "Quick receipt", "dashboard.newServiceOrder": "New service order", "dashboard.ordersInWorkshop": "Orders in workshop", "dashboard.estimatedBilling": "Estimated billing", "dashboard.technicalAgenda": "Technical schedule", "dashboard.pendingQuotes": "Pending quotes", "dashboard.inReception": "in intake", "dashboard.inBench": "on bench", "dashboard.openOrderProducts": "Products and services from open orders", "dashboard.pendingFollowups": "Pending operational follow-ups", "dashboard.customerConfirmation": "Require client confirmation", "dashboard.automatedChannel": "WhatsApp & SMS automated channel active.", "dashboard.keepClientsInformed": "Keep clients informed about every status change.", "dashboard.viewHistory": "View history", "dashboard.activeOrders": "Active work orders", "dashboard.realTimeTracking": "Real-time tracking by repair station", "dashboard.all": "All", "dashboard.reception": "Intake", "dashboard.onBench": "On bench", "dashboard.ready": "Ready", "dashboard.orderDate": "WO / Date", "dashboard.equipmentFault": "Equipment & issue", "dashboard.client": "Client", "dashboard.status": "Status", "dashboard.noEquipment": "Unregistered equipment", "dashboard.noClient": "Unregistered client", "dashboard.noPhone": "No phone", "dashboard.viewAllOrders": "View all queued work orders", "dashboard.currentPriorities": "Current workshop priorities", "dashboard.openAgenda": "Open full schedule", "dashboard.repairBench": "Repair bench", "dashboard.noAssigned": "No assigned equipment", "dashboard.assignOrder": "Assign an order to start a diagnosis.", "dashboard.currentStatus": "Current status", "dashboard.available": "Available", "dashboard.clientFiles": "Clients & records", "dashboard.equipmentRegistered": "Registered equipment", "dashboard.serviceHistory": "service-history records", "dashboard.serialTraceable": "serial-traceable equipment", "dashboard.pendingEstimates": "estimates awaiting approval"
  } }
};

i18n.use(initReactI18next).init({
  resources,
  lng: localStorage.getItem("optifix_language") || "es",
  fallbackLng: "es",
  interpolation: { escapeValue: false }
});

i18n.on("languageChanged", (language) => localStorage.setItem("optifix_language", language));
export default i18n;
